In [2]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# No warnings about setting value on copy of slice
pd.options.mode.chained_assignment = None

# Display up to 60 columns of a dataframe
pd.set_option('display.max_columns', 60)

# Matplotlib visualization
import matplotlib.pyplot as plt
%matplotlib inline

# Set default font size
plt.rcParams['font.size'] = 24

# Internal ipython tool for setting figure size
from IPython.core.pylabtools import figsize

# Seaborn for visualization
import seaborn as sns
sns.set(font_scale = 2)

# Splitting data into training and testing
from sklearn.model_selection import train_test_split

In [3]:
train='Downloads/DSN/train.csv'
test='Downloads/DSN/test.csv'
sub='Downloads/DSN/submission.csv'

In [4]:
train=pd.read_csv(train)
test=pd.read_csv(test)

In [5]:
test.head()

,Applicant_ID,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,form_field11,form_field12,form_field13,form_field14,form_field15,form_field16,form_field17,form_field18,form_field19,form_field20,form_field21,form_field22,form_field23,form_field24,form_field25,form_field26,form_field27,form_field28,form_field29,form_field30,form_field31,form_field32,form_field33,form_field34,form_field35,form_field36,form_field37,form_field38,form_field39,form_field40,form_field41,form_field42,form_field43,form_field44,form_field45,form_field46,form_field47,form_field48,form_field49,form_field50
0,Apcnt_1000032,3236.0,0.34875,10.2006,0.0000,0.0,418564.0,418564.0,418564.0,540710.0,0.0,1649749.0,5446.0,0.0,48187375,114686147.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,1086.0,6204.0,2676.0,60.0,14691.0,9794.0,NaN,238.0,1.8334,0.0,NaN,22.0,2.0,14.0,0.0,NaN,NaN,0.825000,1.01,0.800000,NaN,0.0,charge,NaN,0.000000,0.011221
1,Apcnt_1000048,3284.0,1.27360,2.9606,9.0198,0.0,0.0,9858816.0,49014.0,1510098.0,18308285.0,622789.0,1025793.0,1396510.0,34694910,87479487.0,1.0,1.0,1.0,2.0,2.0,142.560,NaN,NaN,570.585,3082.5,10221.0,6814.0,60.0,11955.0,3528.0,NaN,1216.0,19.5000,3.0,NaN,30.0,18.0,14.0,2.0,NaN,18.8415,0.507694,4.04,0.623248,1.0,0.0,lending,NaN,0.504974,0.043525
2,Apcnt_1000052,NaN,0.27505,0.0600,0.0000,0.0,NaN,NaN,NaN,NaN,0.0,118256.0,NaN,NaN,21973443,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,852.0,4836.0,NaN,NaN,NaN,7.8334,0.0,NaN,2.0,NaN,0.0,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,charge,NaN,0.000000,NaN
3,Apcnt_1000076,3232.0,0.28505,2.8032,0.0000,0.0,0.0,473802.0,473802.0,1724437.0,493641.0,1391064.0,1176725.0,1220293.0,16576457,NaN,2.0,2.0,2.0,3.0,3.0,109.005,13050.00,NaN,109.005,1414.5,4197.0,2798.0,60.0,14964.0,NaN,NaN,248.0,9.0000,1.0,1.0,36.0,0.0,26.0,0.0,NaN,NaN,0.916663,2.02,0.464224,NaN,NaN,charge,90.163742,0.788809,0.104029
4,Apcnt_1000080,3466.0,2.09545,0.8318,2.5182,0.0,19839.0,1150662.0,1150662.0,7860523.0,5752921.0,271133.0,613064.0,4779643.0,48187375,72049802.0,0.0,0.0,0.0,3.0,3.0,139.065,469.29,469.29,15.180,2724.0,9855.0,6570.0,182.0,11679.0,5900.0,NaN,2388.0,16.6666,1.0,0.0,24.0,28.0,20.0,0.0,NaN,NaN,0.234047,23.23,0.726688,0.0,0.0,lending,1303.587148,1.637733,0.163124

In [6]:
train.head()

,Applicant_ID,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,form_field11,form_field12,form_field13,form_field14,form_field15,form_field16,form_field17,form_field18,form_field19,form_field20,form_field21,form_field22,form_field23,form_field24,form_field25,form_field26,form_field27,form_field28,form_field29,form_field30,form_field31,form_field32,form_field33,form_field34,form_field35,form_field36,form_field37,form_field38,form_field39,form_field40,form_field41,form_field42,form_field43,form_field44,form_field45,form_field46,form_field47,form_field48,form_field49,form_field50,default_status
0,Apcnt_1000000,3436.0,0.28505,1.6560,0.0,0.000,0.0,10689720.0,252072.0,4272776.0,11333126.0,4397256.0,2301324.0,7875694.0,96375139,112181765.0,1.0,1.0,1.0,3.0,3.0,134.655,NaN,NaN,134.655,4000.5,17064.0,11376.0,60.0,17064.0,5962.0,NaN,1052.0,8.0000,2.0,NaN,12.0,12.0,4.0,0.0,NaN,NaN,0.392854,2.02,0.711632,0.0,0.0,charge,NaN,1.129518,0.044335,no
1,Apcnt_1000004,3456.0,0.67400,0.2342,0.0,0.000,0.0,898979.0,497531.0,9073814.0,2533168.0,244292.0,3982971.0,2141445.0,28141427,45169902.0,1.0,1.0,1.0,2.0,2.0,109.230,11385.24,14584.29,86.685,4161.0,13413.0,8942.0,304.0,13413.0,5780.0,NaN,2554.0,17.5000,0.0,0.0,16.0,24.0,8.0,0.0,NaN,NaN,0.314281,8.08,0.183584,NaN,0.0,charge,349.805730,1.620483,0.322436,no
2,Apcnt_1000008,3276.0,0.53845,3.1510,0.0,6.282,NaN,956940.0,NaN,192944.0,1079864.0,NaN,NaN,0.0,16576457,22452691.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,1597.5,4746.0,3164.0,60.0,15696.0,NaN,14508.0,70.0,0.6666,0.0,NaN,12.0,0.0,6.0,0.0,149.6805,NaN,0.162965,18.18,0.791136,0.0,0.0,charge,NaN,1.513370,0.011640,yes
3,Apcnt_1000012,3372.0,0.17005,0.5050,0.0,0.000,192166.0,3044703.0,385499.0,3986472.0,3621979.0,NaN,771776.0,1186839.0,48187375,136297820.0,0.0,0.0,0.0,1.0,1.0,120.120,8580.00,0.00,85.800,1701.0,4014.0,2676.0,60.0,11679.0,NaN,NaN,522.0,7.8334,1.0,1.0,4.0,8.0,4.0,1.0,NaN,NaN,0.488884,2.02,0.685168,NaN,0.0,charge,89.940100,0.664452,0.082729,no
4,Apcnt_1000016,3370.0,0.77270,1.1010,0.0,0.000,1556.0,214728.0,214728.0,1284089.0,361770.0,396391.0,818456.0,511535.0,28141427,15292757.0,0.0,0.0,0.0,3.0,3.0,104.535,8360.19,10326.45,115.335,1551.0,3285.0,2190.0,60.0,19437.0,12958.0,5202.0,272.0,1.0000,0.0,0.0,24.0,2.0,24.0,0.0,150.0135,NaN,0.275000,12.12,0.438168,0.0,0.0,charge,97.887502,1.427891,0.045630,no

In [7]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24000 entries, 0 to 23999
Data columns (total 51 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Applicant_ID  24000 non-null  object
 1   form_field1   22890 non-null  float64
 2   form_field2   22291 non-null  float64
 3   form_field3   23854 non-null  float64
 4   form_field4   23854 non-null  float64
 5   form_field5   23854 non-null  float64
 6   form_field6   18396 non-null  float64
 7   form_field7   21769 non-null  float64
 8   form_field8   18396 non-null  float64
 9   form_field9   20600 non-null  float64
 10  form_field10  23853 non-null  float64
 11  form_field11  10602 non-null  float64
 12  form_field12  19817 non-null  float64
 13  form_field13  21537 non-null  float64
 14  form_field14  24000 non-null  int64
 15  form_field15  14408 non-null  float64
 16  form_field16  18526 non-null  float64
 17  form_field17  19305 non-null  float64
 18  form_field18  19631 non-null  float64
 19  form_field19  24000 non-null  float64
 20  form_field20  23853 non-null  float64
 21  form_field21  17293 non-null  float64
 22  form_field22  15276 non-null  float64
 23  form_field23  11875 non-null  float64
 24  form_field24  18395 non-null  float64
 25  form_field25  21744 non-null  float64
 26  form_field26  20828 non-null  float64
 27  form_field27  20090 non-null  float64
 28  form_field28  23853 non-null  float64
 29  form_field29  23853 non-null  float64
 30  form_field30  13092 non-null  float64
 31  form_field31  7190 non-null   float64
 32  form_field32  21744 non-null  float64
 33  form_field33  23505 non-null  float64
 34  form_field34  23853 non-null  float64
 35  form_field35  14134 non-null  float64
 36  form_field36  23097 non-null  float64
 37  form_field37  21744 non-null  float64
 38  form_field38  23853 non-null  float64
 39  form_field39  22171 non-null  float64
 40  form_field40  5172 non-null   float64
 41  form_field41  7651 non-null   float64
 42  form_field42  23422 non-null  float64
 43  form_field43  23750 non-null  float64
 44  form_field44  21638 non-null  float64
 45  form_field45  10462 non-null  float64
 46  form_field46  17115 non-null  float64
 47  form_field47  24000 non-null  object
 48  form_field48  15078 non-null  float64
 49  form_field49  23854 non-null  float64
 50  form_field50  19203 non-null  float64
dtypes: float64(48), int64(1), object(2)
memory usage: 9.3+ MB

In [8]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56000 entries, 0 to 55999
Data columns (total 52 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Applicant_ID    56000 non-null  object
 1   form_field1     53471 non-null  float64
 2   form_field2     52156 non-null  float64
 3   form_field3     55645 non-null  float64
 4   form_field4     55645 non-null  float64
 5   form_field5     55645 non-null  float64
 6   form_field6     42640 non-null  float64
 7   form_field7     50837 non-null  float64
 8   form_field8     42640 non-null  float64
 9   form_field9     47992 non-null  float64
 10  form_field10    55645 non-null  float64
 11  form_field11    24579 non-null  float64
 12  form_field12    46105 non-null  float64
 13  form_field13    50111 non-null  float64
 14  form_field14    56000 non-null  int64
 15  form_field15    33525 non-null  float64
 16  form_field16    42964 non-null  float64
 17  form_field17    44849 non-null  float64
 18  form_field18    45598 non-null  float64
 19  form_field19    55996 non-null  float64
 20  form_field20    55645 non-null  float64
 21  form_field21    40146 non-null  float64
 22  form_field22    35600 non-null  float64
 23  form_field23    27877 non-null  float64
 24  form_field24    42703 non-null  float64
 25  form_field25    50550 non-null  float64
 26  form_field26    48562 non-null  float64
 27  form_field27    46701 non-null  float64
 28  form_field28    55645 non-null  float64
 29  form_field29    55645 non-null  float64
 30  form_field30    30491 non-null  float64
 31  form_field31    16592 non-null  float64
 32  form_field32    50550 non-null  float64
 33  form_field33    54744 non-null  float64
 34  form_field34    55645 non-null  float64
 35  form_field35    32852 non-null  float64
 36  form_field36    54005 non-null  float64
 37  form_field37    50550 non-null  float64
 38  form_field38    55645 non-null  float64
 39  form_field39    51789 non-null  float64
 40  form_field40    12271 non-null  float64
 41  form_field41    17771 non-null  float64
 42  form_field42    54677 non-null  float64
 43  form_field43    55432 non-null  float64
 44  form_field44    50617 non-null  float64
 45  form_field45    24683 non-null  float64
 46  form_field46    40096 non-null  float64
 47  form_field47    56000 non-null  object
 48  form_field48    35111 non-null  float64
 49  form_field49    55645 non-null  float64
 50  form_field50    44944 non-null  float64
 51  default_status  56000 non-null  object
dtypes: float64(48), int64(1), object(3)
memory usage: 22.2+ MB

In [9]:
test.describe()

,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,form_field11,form_field12,form_field13,form_field14,form_field15,form_field16,form_field17,form_field18,form_field19,form_field20,form_field21,form_field22,form_field23,form_field24,form_field25,form_field26,form_field27,form_field28,form_field29,form_field30,form_field31,form_field32,form_field33,form_field34,form_field35,form_field36,form_field37,form_field38,form_field39,form_field40,form_field41,form_field42,form_field43,form_field44,form_field45,form_field46,form_field48,form_field49,form_field50
count,22890.000000,22291.000000,23854.000000,23854.000000,23854.000000,1.839600e+04,2.176900e+04,1.839600e+04,2.060000e+04,2.385300e+04,1.060200e+04,1.981700e+04,2.153700e+04,2.400000e+04,1.440800e+04,18526.000000,19305.000000,19631.000000,24000.000000,23853.000000,17293.000000,15276.000000,11875.000000,18395.000000,21744.000000,20828.000000,20090.000000,23853.000000,23853.000000,13092.000000,7190.000000,21744.000000,23505.000000,23853.000000,14134.000000,23097.000000,21744.000000,23853.000000,22171.000000,5172.000000,7651.000000,23422.000000,23750.000000,21638.000000,10462.000000,17115.000000,1.507800e+04,23854.000000,1.920300e+04
mean,3492.284404,0.557676,1.065443,0.859146,2.183538,6.263036e+05,6.797033e+06,2.654142e+06,1.350593e+07,1.187478e+07,2.132302e+06,2.772047e+06,5.984000e+06,9.291862e+07,1.141483e+08,0.234265,0.267651,0.272477,0.938458,1.020459,87.114080,6653.189477,6473.026142,105.934375,2626.358030,10109.255617,6199.305027,17715.546221,16507.914099,5248.247174,10934.016134,946.711921,14.148066,0.229740,0.194071,12.777157,8.554544,8.506184,0.090749,147.623280,108.209648,0.369684,6.580480,0.566219,0.066526,0.097926,3.015440e+05,1.064118,6.749843e+05
std,190.502764,0.826543,2.198444,3.403115,11.415706,1.457540e+06,1.626022e+07,3.968185e+06,2.289125e+07,2.477113e+07,5.733605e+06,4.794095e+06,1.947650e+07,3.768364e+09,1.194017e+08,0.622532,0.701223,0.706765,1.705298,1.757307,53.179142,5701.118265,5929.962163,479.903878,1946.845869,8787.532233,5388.387561,27153.459422,9672.296721,3138.183322,6168.907825,1057.985881,15.511387,0.671496,0.558517,10.451113,9.469110,7.833898,0.408602,43.580328,36.426276,0.414077,6.363075,0.196060,0.278211,0.370392,1.868574e+06,1.816837,6.561031e+06
min,2986.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.811573e+06,0.000000,0.000000,0.000000,0.000000,0.000000,0.405000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.166600,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.075000,0.000000,0.000000,0.000000,0.066432,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00
25%,3356.000000,0.068675,0.000000,0.000000,0.000000,1.400400e+04,6.725810e+05,1.816630e+05,1.349441e+06,4.208980e+05,2.039332e+05,2.715220e+05,2.007240e+05,1.657646e+07,4.952544e+07,0.000000,0.000000,0.000000,0.000000,0.000000,40.545000,1140.933750,858.157500,14.730000,1231.500000,3375.000000,2068.000000,60.000000,9765.000000,2312.000000,6297.000000,194.000000,2.500000,0.000000,0.000000,6.000000,2.000000,4.000000,0.000000,135.531750,87.499500,0.000000,2.020000,0.413268,0.000000,0.000000,7.272364e+01,0.000000,4.500510e-02
50%,3484.000000,0.273250,0.058200,0.000000,0.000000,1.155330e+05,2.719888e+06,9.594685e+05,5.529830e+06,3.651543e+06,6.727755e+05,1.149495e+06,1.563391e+06,2.814143e+07,8.326778e+07,0.000000,0.000000,0.000000,0.000000,0.000000,90.135000,5918.475000,5561.535000,60.690000,2212.500000,8214.000000,5110.000000,486.000000,15057.000000,5658.000000,10677.000000,600.000000,7.833400,0.000000,0.000000,10.000000,6.000000,6.000000,0.000000,150.000000,117.984000,0.220000,5.050000,0.592100,0.000000,0.000000,3.131754e+02,0.000000,1.680000e-01
75%,3624.000000,0.728850,1.304250,0.000000,0.000000,5.159112e+05,7.073576e+06,3.799849e+06,1.728658e+07,1.318126e+07,1.959393e+06,3.395581e+06,5.582150e+06,4.818738e+07,1.410477e+08,0.000000,0.000000,0.000000,1.000000,1.000000,130.005000,11386.365000,11291.880000,114.990000,3553.500000,14145.000000,8638.000000,60772.000000,21810.000000,7726.000000,14145.000000,1336.000000,21.333400,0.000000,0.000000,16.000000,12.000000,12.000000,0.000000,167.078250,137.207250,0.628573,10.100000,0.756544,0.000000,0.000000,1.195997e+03,1.254155,5.007093e-01
max,3900.000000,22.315050,34.541400,206.452800,297.885600,4.818738e+07,7.709887e+08,1.135141e+08,1.443921e+09,7.741014e+08,1.805987e+08,1.609235e+08,1.387407e+09,3.854990e+11,3.897067e+09,9.000000,10.000000,10.000000,24.000000,24.000000,799.200000,79920.000000,186799.995000,41801.100000,20121.000000,66156.000000,44104.000000,60772.000000,70170.000000,20318.000000,45900.000000,11618.000000,124.000000,15.000000,8.000000,192.000000,120.000000,190.000000,15.000000,401.413500,211.693500,2.200000,91.910000,0.800000,5.000000,19.000000,1.213991e+08,24.000000,2.524591e+08

In [10]:
train.describe()

,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,form_field11,form_field12,form_field13,form_field14,form_field15,form_field16,form_field17,form_field18,form_field19,form_field20,form_field21,form_field22,form_field23,form_field24,form_field25,form_field26,form_field27,form_field28,form_field29,form_field30,form_field31,form_field32,form_field33,form_field34,form_field35,form_field36,form_field37,form_field38,form_field39,form_field40,form_field41,form_field42,form_field43,form_field44,form_field45,form_field46,form_field48,form_field49,form_field50
count,53471.000000,52156.000000,55645.000000,55645.000000,55645.000000,4.264000e+04,5.083700e+04,4.264000e+04,4.799200e+04,5.564500e+04,2.457900e+04,4.610500e+04,5.011100e+04,5.600000e+04,3.352500e+04,42964.000000,44849.000000,45598.000000,55996.000000,55645.000000,40146.000000,35600.000000,27877.000000,42703.000000,50550.000000,48562.000000,46701.000000,55645.000000,55645.000000,30491.000000,16592.000000,50550.000000,54744.000000,55645.000000,32852.000000,54005.000000,50550.000000,55645.000000,51789.000000,12271.000000,17771.000000,54677.000000,55432.000000,50617.000000,24683.000000,40096.000000,3.511100e+04,55645.000000,4.494400e+04
mean,3491.795665,0.550737,1.052225,0.851979,1.956317,6.244479e+05,6.865210e+06,2.626690e+06,1.316002e+07,1.185585e+07,2.054715e+06,2.771113e+06,6.009944e+06,6.914875e+07,1.145041e+08,0.230425,0.265692,0.271832,0.948800,1.031593,86.500380,6628.316381,6452.875072,104.558516,2624.555935,10106.554899,6190.516948,17274.315141,16518.540695,5213.246663,10857.565755,938.345321,13.926583,0.230245,0.199866,12.859069,8.480435,8.601420,0.090849,147.797977,108.117363,0.368215,6.634511,0.563377,0.072520,0.095371,3.052449e+05,1.049061,6.005862e+05
std,188.462426,0.820979,2.147768,3.157692,10.512396,1.433422e+06,1.912729e+07,3.927355e+06,1.977963e+07,2.669459e+07,4.912980e+06,4.544838e+06,2.335893e+07,2.713995e+09,1.153842e+08,0.621833,0.720198,0.725434,1.736454,1.785122,53.445528,5661.059297,5739.968774,436.670719,1964.226548,8796.472481,5390.915344,26930.742020,9666.183962,3124.491488,6049.678489,1044.597044,15.208396,0.683063,0.574002,10.621984,9.328810,7.969215,0.423802,45.085889,36.765769,0.412858,6.378946,0.196973,0.291146,0.335210,1.647757e+06,1.806160,5.842405e+06
min,2990.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.395430e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.255000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.166600,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.021000,0.000000,0.000000,0.000000,0.048528,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00
25%,3358.000000,0.070788,0.000000,0.000000,0.000000,1.400400e+04,6.869740e+05,1.929440e+05,1.368502e+06,4.500730e+05,2.172565e+05,2.758010e+05,1.921660e+05,1.657646e+07,5.007636e+07,0.000000,0.000000,0.000000,0.000000,0.000000,40.305000,1068.667500,797.145000,14.865000,1231.500000,3375.000000,2068.000000,60.000000,9765.000000,2312.000000,6297.000000,194.000000,2.333400,0.000000,0.000000,6.000000,2.000000,4.000000,0.000000,136.191750,87.055500,0.000000,2.020000,0.411672,0.000000,0.000000,7.710079e+01,0.000000,4.560141e-02
50%,3484.000000,0.267575,0.062000,0.000000,0.000000,1.155330e+05,2.704328e+06,9.639420e+05,5.506295e+06,3.707559e+06,6.986440e+05,1.163110e+06,1.605792e+06,2.814143e+07,8.442428e+07,0.000000,0.000000,0.000000,0.000000,0.000000,89.167500,5976.225000,5548.935000,60.660000,2203.500000,8214.000000,5110.000000,486.000000,15057.000000,5658.000000,10584.000000,598.000000,7.833400,0.000000,0.000000,10.000000,6.000000,6.000000,0.000000,150.000000,118.441500,0.220000,5.050000,0.588648,0.000000,0.000000,3.181243e+02,0.000000,1.703996e-01
75%,3620.000000,0.719512,1.282000,0.000000,0.000000,5.259280e+05,6.993831e+06,3.751516e+06,1.694552e+07,1.326101e+07,1.964839e+06,3.360182e+06,5.593626e+06,4.818738e+07,1.428735e+08,0.000000,0.000000,0.000000,1.000000,1.000000,129.892500,11354.171250,11280.000000,114.712500,3517.500000,14145.000000,8700.000000,60772.000000,21810.000000,7726.000000,14235.000000,1332.000000,21.166600,0.000000,0.000000,16.000000,12.000000,12.000000,0.000000,167.754000,137.496750,0.628573,10.100000,0.753840,0.000000,0.000000,1.153022e+03,1.181754,4.993370e-01
max,3900.000000,18.015050,57.371600,91.672200,407.748600,5.313546e+07,2.158794e+09,1.037397e+08,3.200533e+08,2.191361e+09,1.707430e+08,1.240439e+08,2.457824e+09,3.854990e+11,3.456119e+09,11.000000,21.000000,21.000000,28.000000,29.000000,1957.875000,97200.000000,97200.000000,31863.750000,25093.500000,73275.000000,42522.000000,60772.000000,73914.000000,25550.000000,47085.000000,21306.000000,152.000000,21.000000,10.000000,200.000000,106.000000,156.000000,21.000000,645.450000,255.000000,2.200000,91.910000,0.800000,5.000000,5.000000,5.321014e+07,28.000000,2.307571e+08

In [11]:
train.isnull().sum()

Applicant_ID          0
form_field1        2529
form_field2        3844
form_field3         355
form_field4         355
form_field5         355
form_field6       13360
form_field7        5163
form_field8       13360
form_field9        8008
form_field10        355
form_field11      31421
form_field12       9895
form_field13       5889
form_field14          0
form_field15      22475
form_field16      13036
form_field17      11151
form_field18      10402
form_field19          4
form_field20        355
form_field21      15854
form_field22      20400
form_field23      28123
form_field24      13297
form_field25       5450
form_field26       7438
form_field27       9299
form_field28        355
form_field29        355
form_field30      25509
form_field31      39408
form_field32       5450
form_field33       1256
form_field34        355
form_field35      23148
form_field36       1995
form_field37       5450
form_field38        355
form_field39       4211
form_field40      43729
form_field41      38229
form_field42       1323
form_field43        568
form_field44       5383
form_field45      31317
form_field46      15904
form_field47          0
form_field48      20889
form_field49        355
form_field50      11056
default_status        0
dtype: int64

In [12]:
test.isnull().sum()

Applicant_ID        0
form_field1      1110
form_field2      1709
form_field3       146
form_field4       146
form_field5       146
form_field6      5604
form_field7      2231
form_field8      5604
form_field9      3400
form_field10      147
form_field11    13398
form_field12     4183
form_field13     2463
form_field14        0
form_field15     9592
form_field16     5474
form_field17     4695
form_field18     4369
form_field19        0
form_field20      147
form_field21     6707
form_field22     8724
form_field23    12125
form_field24     5605
form_field25     2256
form_field26     3172
form_field27     3910
form_field28      147
form_field29      147
form_field30    10908
form_field31    16810
form_field32     2256
form_field33      495
form_field34      147
form_field35     9866
form_field36      903
form_field37     2256
form_field38      147
form_field39     1829
form_field40    18828
form_field41    16349
form_field42      578
form_field43      250
form_field44     2362
form_field45    13538
form_field46     6885
form_field47        0
form_field48     8922
form_field49      146
form_field50     4797
dtype: int64

In [13]:
# # Missing Values

# Function to calculate missing values by column
def missing_values_table(df):
        # Total missing values
        mis_val = df.isnull().sum()
        
        # Percentage of missing values
        mis_val_percent = 100 * df.isnull().sum() / len(df)
        
        # Make a table with the results
        mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
        
        # Rename the columns
        mis_val_table_ren_columns = mis_val_table.rename(
        columns = {0 : 'Missing Values', 1 : '% of Total Values'})
        
        # Sort the table by percentage of missing descending
        mis_val_table_ren_columns = mis_val_table_ren_columns[
            mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
        '% of Total Values', ascending=False).round(1)
        
        # Print some summary information
        print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n"      
            "There are " + str(mis_val_table_ren_columns.shape[0]) +
              " columns that have missing values.")
         # Return the dataframe with missing information
        return mis_val_table_ren_columns

In [14]:
missing_values_table(test).head(50)

Your selected dataframe has 51 columns.
There are 47 columns that have missing values.

              Missing Values  % of Total Values
form_field40           18828               78.4
form_field31           16810               70.0
form_field41           16349               68.1
form_field45           13538               56.4
form_field11           13398               55.8
form_field23           12125               50.5
form_field30           10908               45.4
form_field35            9866               41.1
form_field15            9592               40.0
form_field48            8922               37.2
form_field22            8724               36.4
form_field46            6885               28.7
form_field21            6707               27.9
form_field24            5605               23.4
form_field8             5604               23.4
form_field6             5604               23.4
form_field16            5474               22.8
form_field50            4797               20.0
form_field17            4695               19.6
form_field18            4369               18.2
form_field12            4183               17.4
form_field27            3910               16.3
form_field9             3400               14.2
form_field26            3172               13.2
form_field13            2463               10.3
form_field44            2362                9.8
form_field25            2256                9.4
form_field32            2256                9.4
form_field37            2256                9.4
form_field7             2231                9.3
form_field39            1829                7.6
form_field2             1709                7.1
form_field1             1110                4.6
form_field36             903                3.8
form_field42             578                2.4
form_field33             495                2.1
form_field43             250                1.0
form_field34             147                0.6
form_field28             147                0.6
form_field10             147                0.6
form_field20             147                0.6
form_field29             147                0.6
form_field38             147                0.6
form_field5              146                0.6
form_field4              146                0.6
form_field3              146                0.6
form_field49             146                0.6

In [15]:
test.fillna(-999, inplace=True)

In [16]:
missing_values_table(train).head(50)

Your selected dataframe has 52 columns.
There are 48 columns that have missing values.

              Missing Values  % of Total Values
form_field40           43729               78.1
form_field31           39408               70.4
form_field41           38229               68.3
form_field11           31421               56.1
form_field45           31317               55.9
form_field23           28123               50.2
form_field30           25509               45.6
form_field35           23148               41.3
form_field15           22475               40.1
form_field48           20889               37.3
form_field22           20400               36.4
form_field46           15904               28.4
form_field21           15854               28.3
form_field6            13360               23.9
form_field8            13360               23.9
form_field24           13297               23.7
form_field16           13036               23.3
form_field17           11151               19.9
form_field50           11056               19.7
form_field18           10402               18.6
form_field12            9895               17.7
form_field27            9299               16.6
form_field9             8008               14.3
form_field26            7438               13.3
form_field13            5889               10.5
form_field25            5450                9.7
form_field32            5450                9.7
form_field37            5450                9.7
form_field44            5383                9.6
form_field7             5163                9.2
form_field39            4211                7.5
form_field2             3844                6.9
form_field1             2529                4.5
form_field36            1995                3.6
form_field42            1323                2.4
form_field33            1256                2.2
form_field43             568                1.0
form_field34             355                0.6
form_field20             355                0.6
form_field10             355                0.6
form_field29             355                0.6
form_field28             355                0.6
form_field5              355                0.6
form_field4              355                0.6
form_field3              355                0.6
form_field49             355                0.6
form_field38             355                0.6
form_field19               4                0.0

In [17]:
train.fillna(-999, inplace=True)

In [18]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24000 entries, 0 to 23999
Data columns (total 51 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Applicant_ID  24000 non-null  object
 1   form_field1   24000 non-null  float64
 2   form_field2   24000 non-null  float64
 3   form_field3   24000 non-null  float64
 4   form_field4   24000 non-null  float64
 5   form_field5   24000 non-null  float64
 6   form_field6   24000 non-null  float64
 7   form_field7   24000 non-null  float64
 8   form_field8   24000 non-null  float64
 9   form_field9   24000 non-null  float64
 10  form_field10  24000 non-null  float64
 11  form_field11  24000 non-null  float64
 12  form_field12  24000 non-null  float64
 13  form_field13  24000 non-null  float64
 14  form_field14  24000 non-null  int64
 15  form_field15  24000 non-null  float64
 16  form_field16  24000 non-null  float64
 17  form_field17  24000 non-null  float64
 18  form_field18  24000 non-null  float64
 19  form_field19  24000 non-null  float64
 20  form_field20  24000 non-null  float64
 21  form_field21  24000 non-null  float64
 22  form_field22  24000 non-null  float64
 23  form_field23  24000 non-null  float64
 24  form_field24  24000 non-null  float64
 25  form_field25  24000 non-null  float64
 26  form_field26  24000 non-null  float64
 27  form_field27  24000 non-null  float64
 28  form_field28  24000 non-null  float64
 29  form_field29  24000 non-null  float64
 30  form_field30  24000 non-null  float64
 31  form_field31  24000 non-null  float64
 32  form_field32  24000 non-null  float64
 33  form_field33  24000 non-null  float64
 34  form_field34  24000 non-null  float64
 35  form_field35  24000 non-null  float64
 36  form_field36  24000 non-null  float64
 37  form_field37  24000 non-null  float64
 38  form_field38  24000 non-null  float64
 39  form_field39  24000 non-null  float64
 40  form_field40  24000 non-null  float64
 41  form_field41  24000 non-null  float64
 42  form_field42  24000 non-null  float64
 43  form_field43  24000 non-null  float64
 44  form_field44  24000 non-null  float64
 45  form_field45  24000 non-null  float64
 46  form_field46  24000 non-null  float64
 47  form_field47  24000 non-null  object
 48  form_field48  24000 non-null  float64
 49  form_field49  24000 non-null  float64
 50  form_field50  24000 non-null  float64
dtypes: float64(48), int64(1), object(2)
memory usage: 9.3+ MB

In [19]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56000 entries, 0 to 55999
Data columns (total 52 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Applicant_ID    56000 non-null  object
 1   form_field1     56000 non-null  float64
 2   form_field2     56000 non-null  float64
 3   form_field3     56000 non-null  float64
 4   form_field4     56000 non-null  float64
 5   form_field5     56000 non-null  float64
 6   form_field6     56000 non-null  float64
 7   form_field7     56000 non-null  float64
 8   form_field8     56000 non-null  float64
 9   form_field9     56000 non-null  float64
 10  form_field10    56000 non-null  float64
 11  form_field11    56000 non-null  float64
 12  form_field12    56000 non-null  float64
 13  form_field13    56000 non-null  float64
 14  form_field14    56000 non-null  int64
 15  form_field15    56000 non-null  float64
 16  form_field16    56000 non-null  float64
 17  form_field17    56000 non-null  float64
 18  form_field18    56000 non-null  float64
 19  form_field19    56000 non-null  float64
 20  form_field20    56000 non-null  float64
 21  form_field21    56000 non-null  float64
 22  form_field22    56000 non-null  float64
 23  form_field23    56000 non-null  float64
 24  form_field24    56000 non-null  float64
 25  form_field25    56000 non-null  float64
 26  form_field26    56000 non-null  float64
 27  form_field27    56000 non-null  float64
 28  form_field28    56000 non-null  float64
 29  form_field29    56000 non-null  float64
 30  form_field30    56000 non-null  float64
 31  form_field31    56000 non-null  float64
 32  form_field32    56000 non-null  float64
 33  form_field33    56000 non-null  float64
 34  form_field34    56000 non-null  float64
 35  form_field35    56000 non-null  float64
 36  form_field36    56000 non-null  float64
 37  form_field37    56000 non-null  float64
 38  form_field38    56000 non-null  float64
 39  form_field39    56000 non-null  float64
 40  form_field40    56000 non-null  float64
 41  form_field41    56000 non-null  float64
 42  form_field42    56000 non-null  float64
 43  form_field43    56000 non-null  float64
 44  form_field44    56000 non-null  float64
 45  form_field45    56000 non-null  float64
 46  form_field46    56000 non-null  float64
 47  form_field47    56000 non-null  object
 48  form_field48    56000 non-null  float64
 49  form_field49    56000 non-null  float64
 50  form_field50    56000 non-null  float64
 51  default_status  56000 non-null  object
dtypes: float64(48), int64(1), object(3)
memory usage: 22.2+ MB

In [20]:
train.head()

,Applicant_ID,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,form_field11,form_field12,form_field13,form_field14,form_field15,form_field16,form_field17,form_field18,form_field19,form_field20,form_field21,form_field22,form_field23,form_field24,form_field25,form_field26,form_field27,form_field28,form_field29,form_field30,form_field31,form_field32,form_field33,form_field34,form_field35,form_field36,form_field37,form_field38,form_field39,form_field40,form_field41,form_field42,form_field43,form_field44,form_field45,form_field46,form_field47,form_field48,form_field49,form_field50,default_status
0,Apcnt_1000000,3436.0,0.28505,1.6560,0.0,0.000,0.0,10689720.0,252072.0,4272776.0,11333126.0,4397256.0,2301324.0,7875694.0,96375139,112181765.0,1.0,1.0,1.0,3.0,3.0,134.655,-999.00,-999.00,134.655,4000.5,17064.0,11376.0,60.0,17064.0,5962.0,-999.0,1052.0,8.0000,2.0,-999.0,12.0,12.0,4.0,0.0,-999.0000,-999.0,0.392854,2.02,0.711632,0.0,0.0,charge,-999.000000,1.129518,0.044335,no
1,Apcnt_1000004,3456.0,0.67400,0.2342,0.0,0.000,0.0,898979.0,497531.0,9073814.0,2533168.0,244292.0,3982971.0,2141445.0,28141427,45169902.0,1.0,1.0,1.0,2.0,2.0,109.230,11385.24,14584.29,86.685,4161.0,13413.0,8942.0,304.0,13413.0,5780.0,-999.0,2554.0,17.5000,0.0,0.0,16.0,24.0,8.0,0.0,-999.0000,-999.0,0.314281,8.08,0.183584,-999.0,0.0,charge,349.805730,1.620483,0.322436,no
2,Apcnt_1000008,3276.0,0.53845,3.1510,0.0,6.282,-999.0,956940.0,-999.0,192944.0,1079864.0,-999.0,-999.0,0.0,16576457,22452691.0,-999.0,-999.0,-999.0,0.0,0.0,-999.000,-999.00,-999.00,-999.000,1597.5,4746.0,3164.0,60.0,15696.0,-999.0,14508.0,70.0,0.6666,0.0,-999.0,12.0,0.0,6.0,0.0,149.6805,-999.0,0.162965,18.18,0.791136,0.0,0.0,charge,-999.000000,1.513370,0.011640,yes
3,Apcnt_1000012,3372.0,0.17005,0.5050,0.0,0.000,192166.0,3044703.0,385499.0,3986472.0,3621979.0,-999.0,771776.0,1186839.0,48187375,136297820.0,0.0,0.0,0.0,1.0,1.0,120.120,8580.00,0.00,85.800,1701.0,4014.0,2676.0,60.0,11679.0,-999.0,-999.0,522.0,7.8334,1.0,1.0,4.0,8.0,4.0,1.0,-999.0000,-999.0,0.488884,2.02,0.685168,-999.0,0.0,charge,89.940100,0.664452,0.082729,no
4,Apcnt_1000016,3370.0,0.77270,1.1010,0.0,0.000,1556.0,214728.0,214728.0,1284089.0,361770.0,396391.0,818456.0,511535.0,28141427,15292757.0,0.0,0.0,0.0,3.0,3.0,104.535,8360.19,10326.45,115.335,1551.0,3285.0,2190.0,60.0,19437.0,12958.0,5202.0,272.0,1.0000,0.0,0.0,24.0,2.0,24.0,0.0,150.0135,-999.0,0.275000,12.12,0.438168,0.0,0.0,charge,97.887502,1.427891,0.045630,no

In [21]:
from sklearn.preprocessing import LabelEncoder
train['form_field47'] = LabelEncoder().fit_transform(train['form_field47'])
test['form_field47'] = LabelEncoder().fit_transform(test['form_field47'])
train['default_status'] = LabelEncoder().fit_transform(train['default_status'])

In [22]:
corr_train = train.corr()

In [23]:
corr_train['default_status'].sort_values(ascending=False)

default_status    1.000000
form_field22      0.134407
form_field23      0.129677
form_field40      0.118154
form_field11      0.104666
form_field2       0.073846
form_field31      0.054845
form_field36      0.040382
form_field19      0.026958
form_field38      0.019113
form_field5       0.015713
form_field4       0.009983
form_field3       0.009359
form_field14      0.008272
form_field49      0.007601
form_field20      0.007007
form_field34      0.005449
form_field42     -0.009512
form_field43     -0.012350
form_field41     -0.019508
form_field35     -0.031519
form_field33     -0.032960
form_field50     -0.048947
form_field48     -0.055441
form_field46     -0.073562
form_field12     -0.088259
form_field13     -0.091342
form_field30     -0.101069
form_field44     -0.112267
form_field15     -0.117442
form_field7      -0.120380
form_field24     -0.128646
form_field39     -0.128859
form_field21     -0.135646
form_field1      -0.140965
form_field37     -0.167874
form_field10     -0.169563
form_field6      -0.173197
form_field29     -0.205897
form_field16     -0.207761
form_field17     -0.213428
form_field45     -0.216687
form_field18     -0.218131
form_field28     -0.219221
form_field47     -0.227926
form_field9      -0.228493
form_field27     -0.234193
form_field26     -0.237164
form_field8      -0.238216
form_field25     -0.252104
form_field32     -0.254526
Name: default_status, dtype: float64

In [24]:
def remove_collinear_features(x, threshold):
    y = x['default_status']
    x = x.drop(columns=['default_status'])
    
    corr_matrix = x.corr()
    iters = range(len(corr_matrix.columns), -1)
    drop_col = []
    
    for i in iters:
        for j in range(i):
            item = corr_matrix.iloc[j:(j+1), (i+1):(i+2)]
            col = item.columns
            row = item.index
            val = abs(item.values)
            
            if val >= threshold:
                drop_col.append(col.values[0])
                 
    drops = set(drop_cols)
    x = x.drop(columns = drops)
    
    # Add the score back in to the data
    x['default_status'] = y
               
    return x

In [25]:
def remove_collinear_features(x, threshold):
    '''
    Objective:
        Remove collinear features in a dataframe with a correlation coefficient
        greater than the threshold. Removing collinear features can help a model
        to generalize and improves the interpretability of the model.
        
    Inputs: 
        threshold: any features with correlations greater than this value are removed
    
    Output: 
        dataframe that contains only the non-highly-collinear features
    '''
    
    # Dont want to remove correlations between loss
    y = x['default_status']
    x = x.drop(columns = ['default_status'])
    
    # Calculate the correlation matrix
    corr_matrix = x.corr()
    iters = range(len(corr_matrix.columns) - 1)
    drop_cols = []

    # Iterate through the correlation matrix and compare correlations
    for i in iters:
        for j in range(i):
            item = corr_matrix.iloc[j:(j+1), (i+1):(i+2)]
            col = item.columns
            row = item.index
            val = abs(item.values)
            
            # If correlation exceeds the threshold
            if val >= threshold:
                # Print the correlated features and the correlation value
                # print(col.values[0], "|", row.values[0], "|", round(val[0][0], 2))
                drop_cols.append(col.values[0])

    # Drop one of each pair of correlated columns
    drops = set(drop_cols)
    x = x.drop(columns = drops)
    
    # Add the score back in to the data
    x['default_status'] = y
               
    return x

In [26]:
train = remove_collinear_features(train, 0.6)

In [27]:
train.shape

(56000, 36)

In [28]:
train.head()

,Applicant_ID,form_field1,form_field2,form_field3,form_field4,form_field6,form_field7,form_field8,form_field9,form_field11,form_field12,form_field13,form_field14,form_field15,form_field16,form_field17,form_field19,form_field22,form_field23,form_field25,form_field26,form_field28,form_field30,form_field31,form_field33,form_field35,form_field36,form_field37,form_field41,form_field42,form_field45,form_field46,form_field47,form_field48,form_field50,default_status
0,Apcnt_1000000,3436.0,0.28505,1.6560,0.0,0.0,10689720.0,252072.0,4272776.0,4397256.0,2301324.0,7875694.0,96375139,112181765.0,1.0,1.0,3.0,-999.00,-999.00,4000.5,17064.0,60.0,5962.0,-999.0,8.0000,-999.0,12.0,12.0,-999.0,0.392854,0.0,0.0,0,-999.000000,0.044335,0
1,Apcnt_1000004,3456.0,0.67400,0.2342,0.0,0.0,898979.0,497531.0,9073814.0,244292.0,3982971.0,2141445.0,28141427,45169902.0,1.0,1.0,2.0,11385.24,14584.29,4161.0,13413.0,304.0,5780.0,-999.0,17.5000,0.0,16.0,24.0,-999.0,0.314281,-999.0,0.0,0,349.805730,0.322436,0
2,Apcnt_1000008,3276.0,0.53845,3.1510,0.0,-999.0,956940.0,-999.0,192944.0,-999.0,-999.0,0.0,16576457,22452691.0,-999.0,-999.0,0.0,-999.00,-999.00,1597.5,4746.0,60.0,-999.0,14508.0,0.6666,-999.0,12.0,0.0,-999.0,0.162965,0.0,0.0,0,-999.000000,0.011640,1
3,Apcnt_1000012,3372.0,0.17005,0.5050,0.0,192166.0,3044703.0,385499.0,3986472.0,-999.0,771776.0,1186839.0,48187375,136297820.0,0.0,0.0,1.0,8580.00,0.00,1701.0,4014.0,60.0,-999.0,-999.0,7.8334,1.0,4.0,8.0,-999.0,0.488884,-999.0,0.0,0,89.940100,0.082729,0
4,Apcnt_1000016,3370.0,0.77270,1.1010,0.0,1556.0,214728.0,214728.0,1284089.0,396391.0,818456.0,511535.0,28141427,15292757.0,0.0,0.0,3.0,8360.19,10326.45,1551.0,3285.0,60.0,12958.0,5202.0,1.0000,0.0,24.0,2.0,-999.0,0.275000,0.0,0.0,0,97.887502,0.045630,0

In [29]:
features = train.select_dtypes(exclude = object).columns.drop(['default_status'])

In [30]:
X = train[features]
y = train['default_status']

In [31]:
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score
from catboost import CatBoostClassifier

In [32]:
def metric(y, pred):
    return roc_auc_score(y, pred, labels=[0, 1])

In [33]:
# Specify number of folds
n_skf = 5
kf = StratifiedKFold(n_skf)


seed = 2020

## Manually tweak the hyperparameter, learning rate and n_estimators especially
params = {
    'n_estimators': 4000,
    'learning_rate': 0.01,
    'objective': 'CrossEntropy',
      'eval_metric':'AUC',
    'random_seed': seed,
    'early_stopping_rounds': 200,
    'use_best_model': True,
}

In [ ]:
score_list = []
score = 0
test_oofs = []

for i, (tr_idx, vr_idx) in enumerate(kf.split(X, y)):
    
    xtrain, ytrain = X.loc[tr_idx, features], y.loc[tr_idx]
    xval, yval = X.loc[vr_idx, features], y.loc[vr_idx]

    model = CatBoostClassifier(**params)
    model.fit(xtrain, ytrain, eval_set=[(xval,yval)], verbose=100)
    
    p = model.predict_proba(xval)[:, 1]
    sc = metric(yval, p)
    score_list.append(sc)
    score += sc/n_skf
    
    pred = model.predict_proba(test[features])[:, 1]
    test_oofs.append(pred)

    print('Fold {} : {}'.format(i, sc))

print()
print()
print('Avg log : ', score)